spring:
  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari.maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail: somemail@wp.pl
server.port: 8091
